/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tests;

import org.apache.commons.lang3.tuple.Pair;
import org.testng.Assert;
import org.testng.annotations.*;

import page.CarListPage;
import page.MainComponent;
import page.WebPageComponent;
import main.Message;
import main.Main;

import java.sql.SQLException;

public class AppTest extends Main {

	@Test public void gameSmoke() throws InterruptedException, SQLException {

		WebPageComponent webpage = new WebPageComponent(driver);
		MainComponent mainpage = new MainComponent(driver);
		CarListPage carListPage = new CarListPage(driver);

		webpage.open_page();
		Thread.sleep(14000);

		mainpage.acceptCookies();
		//Step1
		mainpage.chooseNadwozie("Sedan");
		mainpage.chooseMarka("Renault");
		mainpage.chooseModel("Megane");
		mainpage.chooseGeneracja("IV");
		mainpage.buttonSubmit2.click();
		//Step2
		Thread.sleep(10000);
		carListPage.scrapePage();

	}

}
